//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CradlAI.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CradlAI.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication_Category {
            get {
                return ResourceManager.GetString("Authentication_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, continue executing the remaining activities even if the current activity has failed..
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinueOnError.
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ListFlows_ClientId_Description {
            get {
                return ResourceManager.GetString("ListFlows_ClientId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clientId.
        /// </summary>
        public static string ListFlows_ClientId_DisplayName {
            get {
                return ResourceManager.GetString("ListFlows_ClientId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ListFlows_ClientSecret_Description {
            get {
                return ResourceManager.GetString("ListFlows_ClientSecret_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clientSecret.
        /// </summary>
        public static string ListFlows_ClientSecret_DisplayName {
            get {
                return ResourceManager.GetString("ListFlows_ClientSecret_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ListFlows_Description {
            get {
                return ResourceManager.GetString("ListFlows_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListFlows.
        /// </summary>
        public static string ListFlows_DisplayName {
            get {
                return ResourceManager.GetString("ListFlows_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ListFlows_Endpoint_Description {
            get {
                return ResourceManager.GetString("ListFlows_Endpoint_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to endpoint.
        /// </summary>
        public static string ListFlows_Endpoint_DisplayName {
            get {
                return ResourceManager.GetString("ListFlows_Endpoint_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ListProcessedDocuments_ClientId_Description {
            get {
                return ResourceManager.GetString("ListProcessedDocuments_ClientId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clientId.
        /// </summary>
        public static string ListProcessedDocuments_ClientId_DisplayName {
            get {
                return ResourceManager.GetString("ListProcessedDocuments_ClientId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ListProcessedDocuments_ClientSecret_Description {
            get {
                return ResourceManager.GetString("ListProcessedDocuments_ClientSecret_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clientSecret.
        /// </summary>
        public static string ListProcessedDocuments_ClientSecret_DisplayName {
            get {
                return ResourceManager.GetString("ListProcessedDocuments_ClientSecret_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ListProcessedDocuments_Description {
            get {
                return ResourceManager.GetString("ListProcessedDocuments_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListProcessedDocuments.
        /// </summary>
        public static string ListProcessedDocuments_DisplayName {
            get {
                return ResourceManager.GetString("ListProcessedDocuments_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ListProcessedDocuments_Status_Description {
            get {
                return ResourceManager.GetString("ListProcessedDocuments_Status_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clientId.
        /// </summary>
        public static string ListProcessedDocuments_Status_DisplayName {
            get {
                return ResourceManager.GetString("ListProcessedDocuments_Status_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ListProcessedDocuments_FlowId_Description {
            get {
                return ResourceManager.GetString("ListProcessedDocuments_FlowId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clientId.
        /// </summary>
        public static string ListProcessedDocuments_FlowId_DisplayName {
            get {
                return ResourceManager.GetString("ListProcessedDocuments_FlowId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ListProcessedDocuments_Runs_Description {
            get {
                return ResourceManager.GetString("ListProcessedDocuments_Runs_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clientId.
        /// </summary>
        public static string ListProcessedDocuments_Runs_DisplayName {
            get {
                return ResourceManager.GetString("ListProcessedDocuments_Runs_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MarkRunAsCompleted_ClientId_Description {
            get {
                return ResourceManager.GetString("MarkRunAsCompleted_ClientId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clientId.
        /// </summary>
        public static string MarkRunAsCompleted_ClientId_DisplayName {
            get {
                return ResourceManager.GetString("MarkRunAsCompleted_ClientId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MarkRunAsCompleted_ClientSecret_Description {
            get {
                return ResourceManager.GetString("MarkRunAsCompleted_ClientSecret_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clientSecret.
        /// </summary>
        public static string MarkRunAsCompleted_ClientSecret_DisplayName {
            get {
                return ResourceManager.GetString("MarkRunAsCompleted_ClientSecret_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MarkRunAsCompleted_Description {
            get {
                return ResourceManager.GetString("MarkRunAsCompleted_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MarkRunAsCompleted.
        /// </summary>
        public static string MarkRunAsCompleted_DisplayName {
            get {
                return ResourceManager.GetString("MarkRunAsCompleted_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MarkRunAsCompleted_FlowId_Description {
            get {
                return ResourceManager.GetString("MarkRunAsCompleted_FlowId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clientSecret.
        /// </summary>
        public static string MarkRunAsCompleted_FlowId_DisplayName {
            get {
                return ResourceManager.GetString("MarkRunAsCompleted_FlowId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MarkRunAsCompleted_RunId_Description {
            get {
                return ResourceManager.GetString("MarkRunAsCompleted_RunId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clientSecret.
        /// </summary>
        public static string MarkRunAsCompleted_RunId_DisplayName {
            get {
                return ResourceManager.GetString("MarkRunAsCompleted_RunId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MarkRunAsCompleted_Status_Description {
            get {
                return ResourceManager.GetString("MarkRunAsCompleted_Status_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clientSecret.
        /// </summary>
        public static string MarkRunAsCompleted_Status_DisplayName {
            get {
                return ResourceManager.GetString("MarkRunAsCompleted_Status_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MarkRunAsCompleted_Run_Description {
            get {
                return ResourceManager.GetString("MarkRunAsCompleted_Run_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clientSecret.
        /// </summary>
        public static string MarkRunAsCompleted_Run_DisplayName {
            get {
                return ResourceManager.GetString("MarkRunAsCompleted_Run_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParseDocumentWithHumanInTheLoop_ClientId_Description {
            get {
                return ResourceManager.GetString("ParseDocumentWithHumanInTheLoop_ClientId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clientId.
        /// </summary>
        public static string ParseDocumentWithHumanInTheLoop_ClientId_DisplayName {
            get {
                return ResourceManager.GetString("ParseDocumentWithHumanInTheLoop_ClientId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParseDocumentWithHumanInTheLoop_ClientSecret_Description {
            get {
                return ResourceManager.GetString("ParseDocumentWithHumanInTheLoop_ClientSecret_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clientSecret.
        /// </summary>
        public static string ParseDocumentWithHumanInTheLoop_ClientSecret_DisplayName {
            get {
                return ResourceManager.GetString("ParseDocumentWithHumanInTheLoop_ClientSecret_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParseDocumentWithHumanInTheLoop_Description {
            get {
                return ResourceManager.GetString("ParseDocumentWithHumanInTheLoop_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParseDocumentWithHumanInTheLoop.
        /// </summary>
        public static string ParseDocumentWithHumanInTheLoop_DisplayName {
            get {
                return ResourceManager.GetString("ParseDocumentWithHumanInTheLoop_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParseDocumentWithHumanInTheLoop_FlowId_Description {
            get {
                return ResourceManager.GetString("ParseDocumentWithHumanInTheLoop_FlowId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clientSecret.
        /// </summary>
        public static string ParseDocumentWithHumanInTheLoop_FlowId_DisplayName {
            get {
                return ResourceManager.GetString("ParseDocumentWithHumanInTheLoop_FlowId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParseDocumentWithHumanInTheLoop_DocumentId_Description {
            get {
                return ResourceManager.GetString("ParseDocumentWithHumanInTheLoop_DocumentId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clientSecret.
        /// </summary>
        public static string ParseDocumentWithHumanInTheLoop_DocumentId_DisplayName {
            get {
                return ResourceManager.GetString("ParseDocumentWithHumanInTheLoop_DocumentId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParseDocumentWithHumanInTheLoop_FilePath_Description {
            get {
                return ResourceManager.GetString("ParseDocumentWithHumanInTheLoop_FilePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clientSecret.
        /// </summary>
        public static string ParseDocumentWithHumanInTheLoop_FilePath_DisplayName {
            get {
                return ResourceManager.GetString("ParseDocumentWithHumanInTheLoop_FilePath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParseDocumentWithHumanInTheLoop_Content_Description {
            get {
                return ResourceManager.GetString("ParseDocumentWithHumanInTheLoop_Content_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clientSecret.
        /// </summary>
        public static string ParseDocumentWithHumanInTheLoop_Content_DisplayName {
            get {
                return ResourceManager.GetString("ParseDocumentWithHumanInTheLoop_Content_DisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParseDocumentWithHumanInTheLoop_Run_Description {
            get {
                return ResourceManager.GetString("ParseDocumentWithHumanInTheLoop_Run_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clientSecret.
        /// </summary>
        public static string ParseDocumentWithHumanInTheLoop_Run_DisplayName {
            get {
                return ResourceManager.GetString("ParseDocumentWithHumanInTheLoop_Run_DisplayName", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options_Category {
            get {
                return ResourceManager.GetString("Options_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParseDocument_ClientId_Description {
            get {
                return ResourceManager.GetString("ParseDocument_ClientId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clientId.
        /// </summary>
        public static string ParseDocument_ClientId_DisplayName {
            get {
                return ResourceManager.GetString("ParseDocument_ClientId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParseDocument_ClientSecret_Description {
            get {
                return ResourceManager.GetString("ParseDocument_ClientSecret_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clientSecret.
        /// </summary>
        public static string ParseDocument_ClientSecret_DisplayName {
            get {
                return ResourceManager.GetString("ParseDocument_ClientSecret_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParseDocument_Description {
            get {
                return ResourceManager.GetString("ParseDocument_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse Document.
        /// </summary>
        public static string ParseDocument_DisplayName {
            get {
                return ResourceManager.GetString("ParseDocument_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParseDocument_DocumentId_Description {
            get {
                return ResourceManager.GetString("ParseDocument_DocumentId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to documentId.
        /// </summary>
        public static string ParseDocument_DocumentId_DisplayName {
            get {
                return ResourceManager.GetString("ParseDocument_DocumentId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParseDocument_Content_Description {
            get {
                return ResourceManager.GetString("ParseDocument_Content_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.
        /// </summary>
        public static string ParseDocument_Content_DisplayName {
            get {
                return ResourceManager.GetString("ParseDocument_Content_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParseDocument_ModelId_Description {
            get {
                return ResourceManager.GetString("ParseDocument_ModelId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modelId.
        /// </summary>
        public static string ParseDocument_ModelId_DisplayName {
            get {
                return ResourceManager.GetString("ParseDocument_ModelId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParseDocument_FilePath_Description {
            get {
                return ResourceManager.GetString("ParseDocument_FilePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to documentId.
        /// </summary>
        public static string ParseDocument_FilePath_DisplayName {
            get {
                return ResourceManager.GetString("ParseDocument_FilePath_DisplayName", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ParseDocument_Predictions_Description {
            get {
                return ResourceManager.GetString("ParseDocument_Predictions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to predictions.
        /// </summary>
        public static string ParseDocument_Predictions_DisplayName {
            get {
                return ResourceManager.GetString("ParseDocument_Predictions_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the amount of time (in milliseconds) to wait for the activity to run before an error is thrown. The default value is 60000 (1 minute)..
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (milliseconds).
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity timed out and was canceled..
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value either for {0} or {1}, but not both..
        /// </summary>
        public static string ValidationExclusiveProperties_Error {
            get {
                return ResourceManager.GetString("ValidationExclusiveProperties_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide values for both {0} and {1}..
        /// </summary>
        public static string ValidationOverloadGroup_Error {
            get {
                return ResourceManager.GetString("ValidationOverloadGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be used outside of a {0}..
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}..
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
    }
}
